[package]
name = "mctp_transport"
version = "0.1.0"
authors = [
    "Xiaoyu Lu <xiaoyux.lu@intel.com>",
    "Jiewen Yao <jiewen.yao@intel.com>"
    ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = { version = "0.9.8" }
codec = {path= "../codec"}
spdmlib = { path = "../spdmlib", default-features = false}
futures = { version = "0.3", default-features = false }
async-trait = "0.1.71"
executor = { path = "../executor" }
