name: FUZZING CODE

on:
  push:
    branches: ["master"]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  fuzzing_test:
    strategy:
      matrix:
        fuzz_hash_transcript_data_feature: [true, false]
        fuzz_mut_auth_feature: [true, false]

    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check code
        run: |
          ./sh_script/build.sh -c

      - name: Run fuzz
        env:
          FUZZ_HASH_TRANSCRIPT_DATA_FEATURE: ${{ matrix.fuzz_hash_transcript_data_feature }}
          FUZZ_MUT_AUTH_FEATURE: ${{ matrix.fuzz_mut_auth_feature }}
        run: |
          ./sh_script/fuzz_run.sh
